# -*- coding: utf-8 -*-
"""face musk detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18P46RopLLpJVpY821EfX8UOaAaBA6LLp
"""

import numpy as np
import tensorflow as tf
import os
import imageio
import matplotlib.pyplot as plt
import kagglehub

from tensorflow.keras.layers import (
    Input,
    Conv2D,
    MaxPooling2D,
    Dropout,
    Conv2DTranspose,
    concatenate
)

from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from sklearn.model_selection import train_test_split

dataset_path = kagglehub.dataset_download(
    "wobotintelligence/face-mask-detection-dataset"
)

print("Dataset Path:", dataset_path)

# ============================================
# CHECK DATASET CONTENTS
# ============================================

for root, dirs, files in os.walk(dataset_path):
    print("Folder:", root)
    print("Files:", files[:5])
    print("-" * 50)
    break

image_paths = []

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.endswith((".png", ".jpg", ".jpeg")):
            image_paths.append(os.path.join(root, file))

print("Total Images Found:", len(image_paths))

print("\nDataset folders:")
print(os.listdir(dataset_path))

sample_image = imageio.imread(image_paths[0])

plt.figure(figsize=(6,6))
plt.imshow(sample_image)
plt.title("Sample Image")
plt.axis("off")
plt.show()

IMG_HEIGHT = 128
IMG_WIDTH = 128
IMG_CHANNELS = 3

X = []

# Using first 100 images for demo
for path in image_paths[:100]:

    img = load_img(
        path,
        target_size=(IMG_HEIGHT, IMG_WIDTH)
    )

    img = img_to_array(img)
    img = img / 255.0

    X.append(img)

X = np.array(X)

print("Shape of X:", X.shape)

y = np.random.randint(
    0,
    2,
    (len(X), IMG_HEIGHT, IMG_WIDTH, 1)
)

print("Shape of y:", y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

inputs = Input((IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS))

# --------------------------------------------
# ENCODER
# --------------------------------------------

c1 = Conv2D(16, (3,3), activation='relu', padding='same')(inputs)
c1 = Dropout(0.1)(c1)
c1 = Conv2D(16, (3,3), activation='relu', padding='same')(c1)
p1 = MaxPooling2D((2,2))(c1)

c2 = Conv2D(32, (3,3), activation='relu', padding='same')(p1)
c2 = Dropout(0.1)(c2)
c2 = Conv2D(32, (3,3), activation='relu', padding='same')(c2)
p2 = MaxPooling2D((2,2))(c2)

# --------------------------------------------
# BOTTLENECK
# --------------------------------------------

c3 = Conv2D(64, (3,3), activation='relu', padding='same')(p2)
c3 = Dropout(0.2)(c3)
c3 = Conv2D(64, (3,3), activation='relu', padding='same')(c3)

# --------------------------------------------
# DECODER
# --------------------------------------------

u4 = Conv2DTranspose(
    32,
    (2,2),
    strides=(2,2),
    padding='same'
)(c3)

u4 = concatenate([u4, c2])

c4 = Conv2D(32, (3,3), activation='relu', padding='same')(u4)
c4 = Dropout(0.1)(c4)
c4 = Conv2D(32, (3,3), activation='relu', padding='same')(c4)

u5 = Conv2DTranspose(
    16,
    (2,2),
    strides=(2,2),
    padding='same'
)(c4)

u5 = concatenate([u5, c1])

c5 = Conv2D(16, (3,3), activation='relu', padding='same')(u5)
c5 = Dropout(0.1)(c5)
c5 = Conv2D(16, (3,3), activation='relu', padding='same')(c5)

# --------------------------------------------
# OUTPUT LAYER
# --------------------------------------------

outputs = Conv2D(
    1,
    (1,1),
    activation='sigmoid'
)(c5)

# ============================================
# CREATE MODEL
# ============================================

model = Model(inputs=[inputs], outputs=[outputs])

# ============================================
# COMPILE MODEL
# ============================================

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# ============================================
# MODEL SUMMARY
# ============================================

model.summary()

# ============================================
# TRAIN MODEL
# ============================================

results = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    batch_size=8,
    epochs=10
)

# ============================================
# EVALUATE MODEL
# ============================================

loss, accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

# ============================================
# PREDICTIONS
# ============================================

predictions = model.predict(X_test)

# ============================================
# SHOW PREDICTION
# ============================================

plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.imshow(X_test[0])
plt.title("Input Image")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(y_test[0].squeeze(), cmap='gray')
plt.title("True Mask")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(predictions[0].squeeze(), cmap='gray')
plt.title("Predicted Mask")
plt.axis("off")

plt.show()